/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package graficas;

import visual.*;
import graficas.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author denil
 */
public class graficas extends javax.swing.JPanel {
lexico lexico = new lexico();


private final String[] palabrasClave = {
    "as","assert","break","class","continue","def","def","del","elif",
    "else","except","False","finally","for","from","global","if","import","in",
    "is","lamda","None","nonlocal","pass","raise","return","True",
    "try","while","with","yield"    
    };
    /**
     * Creates new form graficos
     */
    public graficas() {
        initComponents();
        llamada();
     
    
    }
  
    
    public void llamada(){
           for (String claves : palabrasClave){
            clav.addItem(claves);
        
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clav1 = new javax.swing.JComboBox<>();
        clav = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        pepe = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1100, 700));
        setPreferredSize(new java.awt.Dimension(1100, 700));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clav1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clav1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clav1ActionPerformed(evt);
            }
        });
        jPanel1.add(clav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 190, 80));

        clav.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavActionPerformed(evt);
            }
        });
        jPanel1.add(clav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 80));

        jButton1.setText("Generar Gráfica");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, -1));

        pepe.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(pepe, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 340, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("PROXIMAMAENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 650, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clavActionPerformed
        // TODO add your handling code here:
        int opciones = clav.getSelectedIndex();
        String opcionClave = clav.getSelectedItem().toString();
        
        pepe.setText(String.valueOf(opcionClave));
        
    }//GEN-LAST:event_clavActionPerformed

    private void clav1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clav1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clav1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> clav;
    private javax.swing.JComboBox<String> clav1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pepe;
    // End of variables declaration//GEN-END:variables
}
